# Generated by Django 3.2.6 on 2021-08-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
