# Generated by Django 3.2.6 on 2021-09-09 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_facts_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('document', models.FileField(unique=True, upload_to='document/')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
